- slcanpty.c
add v command response. Some software like USBtinViewer using 'v' for software version.
Tested on USBtinViewer 1.0
> add 'v' command response

- lib.h
Ah... I was trying to include lib.h from 2 different headers and ... just noticed...
A header guard would be nice as well. Also including `stdio.h` to handle `FILE` ([ref](https://github.com/linux-can/can-utils/blob/ef2ea8fa59e9123c496a109b2b4cb62dd1e3e7fa/lib.h#L145))
(Thanks for quick previous merge.)
> header-guard for lib.h

- cangen.c
This patch fixes a bug in cangen.c
Bug: When used with -m option, if a CAN FD frame with BRS option set is
sent, that flag never gets cleared for the subsequent frames.
Fix: Reset frame.flags at the start of iteration.
Signed-off-by: Ramesh Shanmugasundaram <ramesh.shanmugasundaram@bp.renesas.com>
> cangen: reset frame flags at the start of iteration

- configure.ac
With glibc versions before 2.17, we get following build error:
canfdtest.o: In function `millisleep':
canfdtest.c:(.text+0x212): undefined reference to `clock_nanosleep'
collect2: error: ld returned 1 exit status
make[1]: *** [canfdtest] Error 1
make[1]: *** Waiting for unfinished jobs....
glibc versions before 2.17 needs to link with -lrt for
clock_nanosleep(). This patch adds support to detect if linking with
librt is required.
This build issue is detected by Buildroot autobuilder:
http://autobuild.buildroot.net/results/0e5/0e5242376ff6aa82e89ed1172350e05009d48156/build-end.log
Signed-off-by: Rahul Bedarkar <rahul.bedarkar@imgtec.com>
> Add check to detect clock_nanosleep() in librt

- isotptun.c
We want isotptun to exit when the tun device can be used. This helps system
startup continue configuration and use of the interface at correct time.
Log errors to syslog when daemonized or to stderr when in foreground.
Exit consistently with EXIT_FAILURE when the tun device was not set up as
defined on the command line.
Signed-off-by: Marko Kohtala <marko.kohtala@gmail.com>
> isotptun: daemonize by default, add -F for old behavior

- lib.c
I was reading the code to learn more about can but I noticed that the hex_asc_upper_lo macro which is defined before do the same thing as  hex_asc_upper[id & 0xF] so it needs to change for standardization
> use a macro for standardization

- cansniffer.c
old code does extra sets and clears in case of quiet==1 so I've changed if statement orders and used else if
> omit extra sets and clears

- slcand.c
ttypath can't fit filenames such as /dev/serial/by-id/usb-Zubax_Robotics_Zubax_Babel_1D002A00185732523935382000000000-if00
> increase TTYPATH_LENGTH

- candump.c
I took the code from https://marc.info/?l=linux-can&m=138244457221323&w=2.
Unfortunately only the pcan driver provides hardware timestamps.
Note that I don't own a PCAN adapter, I tested this modification using a self made pcan compatible adapter, receiving one message every 400 us and the hardware timestamp sometimes jumps back or forward. The same self made adapter gives correct timestamps in Windows with the official driver and PCAN-view.
> Add option to read hardware timestamps.

- GNUmakefile.am
- Makefile
- testj1939.c
canaddr2str() from testj1939 and libj1939's libj1939_addr2str provide
the same functionality. Remove the local helper function and use
libj1939_addr2str instead.
Signed-off-by: Bastian Stender <bst@pengutronix.de>
> testj1939: use address to string function from libj1939

- cansend.c
See issue #75 for more information.
> valgrind no longer reports uninitialised byte(s) from bind call.

- cansend.c
Use memset() instead of bzero().
> bzero() is deprecated

- slcand.c
Delay the daemon() call until the interface has been configured. This
simplifies scripts that wish to use the new interface immediately.
Signed-off-by: Mans Rullgard <mans@mansr.com>
> slcand: daemonise only once setup is complete

- .travis.yml
For now exclude unused-result warnings in order not to
affect current builds.
> CI: treat gcc warnings as errors

- testj1939.c
This options are needed for testing of j1939 socket functionality and currently used by labgrid based j1939 regression testing.
> add bind related options to testj1939

- candump.c
Single char typo, also means of learning the ropes.
> Fix CAN ID typo in candump usage, to 12345678

- testj1939.c
Currently if we set size which is more then 128 byte
will silently ignore provided value and send only maximal
supported size.
> testj1939: fail if we use unsupported size

- testj1939.c
Currently if we send lots of bytes, `test1939` output will get unreadable.
Make it easier to read by splitting output dump.
New format will looks as following example:
```
root@DistroKit:~ testj1939 can0:0x90 -r
80 12300: 01 23 45 67 89 ab cd ef
00008     01 23 45 67 89 ab cd ef
00010     01 23 45 67 89 ab cd ef
00018     01 23 45 67 89 ab cd ef
00020     01 23 45 67 89 ab cd ef
00028     01 23 45 67 89 ab cd ef
00030     01 23 45 67 89 ab cd ef
00038     01 23 45 67 89 ab cd ef
00040     01 23 45 67 89 ab cd ef
00048     01 23 45 67 89 ab cd ef
00050     01 23 45 67 89 ab cd ef
00058     01 23 45 67 89 ab cd ef
00060     01 23 45 67 89 ab cd ef
00068     01 23 45 67 89 ab cd ef
00070     01 23 45 67 89 ab cd ef
00078     01 23 45 67 89 ab cd ef
```
Signed-off-by: Oleksij Rempel …
> testj1939: split output string in to 8 byte strings

- CMakeLists.txt
This library uses `if_nameindex` symbol, not available at this system.
When compiling for Android, you get the following warnings:
```
libj1939.c:35:3: warning: implicit declaration of function 'if_freenameindex' is invalid in C99 [-Wimplicit-function-declaration]
libj1939.c:42:11: warning: implicit declaration of function 'if_nameindex' is invalid in C99 [-Wimplicit-function-declaration]
libj1939.c:42:9: warning: incompatible integer to pointer conversion assigning to 'struct if_nameindex *' from 'int' [-Wint-conversion]
libj1939.c:44:4: warning: implicit declaration of function 'error' is invalid in C99 [-Wimplicit-function-declaration]
```
> Don't build libj1939 for Android

- testj1939.c
This patch uses `%zu` to print the value of `sizeof()`. This works without compiler warnings on 32 and 64 bit systems.
> testj1939: use %zu to as format string to print sizeof()

- libj1939.c
> libj1939: fix name parsing

- isotpdump.c
| isotpdump.c: In function ‘print_uds_message’:
| isotpdump.c:94:29: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
|   } else if (service >= 0x10 && service <= 0x3E ||
|              ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
| isotpdump.c:96:22: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
|       service >= 0xBA && service <= 0xBE)
|       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
> isotpdump: fix compiler warning

- canlogserver.c
- cansniffer.c
- isotpdump.c
- isotpperf.c
- isotpsniffer.c
- slcanpty.c
In linux kernel commit 0768e17073dc527ccd18ed5f96ce85f9985e9115
the asm-generic/sockios.h header no longer defines SIOCGSTAMP.
Instead it provides only SIOCGSTAMP_OLD.
The linux/sockios.h header now defines SIOCGSTAMP using either
SIOCGSTAMP_OLD or SIOCGSTAMP_NEW as appropriate. This linux only
header file is not pulled so we get a build failure.
canlogserver.c: In function 'main':
canlogserver.c:404:21: error: 'SIOCGSTAMP' undeclared (first use in this function); did you mean 'SIOCGRARP'?
if (ioctl(s[i], SIOCGSTAMP, &tv) < 0)
^~~~~~~~~~
SIOCGRARP
canlogserver.c:404:21: note: each undeclared identifier is reported only once for each function it appears in
Fixes:
- http://autobuild.buildroot.org/results/363de7d9bf433be8bc47ba4ee52ae0bb80fa9021
Signed-off-by: Fabrice Fontaine …
> fix include to find SIOCGSTAMP with latest kernel

- jacd.c
- jcat.c
- jspy.c
- jsr.c
- libj1939.c
- testj1939.c
Fixes: https://github.com/linux-can/can-utils/issues/161
Reported-by: Brandon Ros <brandonros1@gmail.com>
> treewide: Fix compilation on libmusl, replace error() by err()

- README.md
- bcmserver.c
- can-j1939-kickstart.md
- can-j1939.md
- canbusload.c
- candump.c
- cangw.c
- canplayer.c
- isotprecv.c
- isotpserver.c
- isotpsniffer.c
- jspy.c
- lib.h
- slcanpty.c
codespell parameters:
`codespell -q 3 --skip="*.in,*.sh,*.m4,config,configure,autom4te.cache"`
> Fix spelling in various files

- jacd.c
> jacd: fix typo in a comment

- libj1939.c
Include err.h and remove the unneeded parameter errno and
its header include.
Fixes: 791b6de ("treewide: Fix compilation on libmusl, replace error() by err()")
> libj1939: fix missing include and syntax

- isotpsniffer.c
Fixes: b04108c6150d ("isotpsniffer: Fix error handling")
> isotpsniffer: fix error handling, "0" is a valid filedescriptor

- jacd.c
This was used in the non mainline stack version.
Removing this call allows to use jacd without root permissions.
> jacd: remove SO_BINDTODEVICE setsockopt call

- .github/workflows/autotools.yml
This enables a simple GitHub action, which just runs `make` and `make distcheck`. The results will be visible in the pull request view. As an exampe, see [the PR page](https://github.com/jluebbe/can-utils/pull/1) and [the checks page](https://github.com/jluebbe/can-utils/pull/1/checks) in my fork.
> add github actions

- .gitignore
- CMakeLists.txt
- GNUmakefile.am
- Makefile
- j1939acd.c
- j1939cat.c
- j1939spy.c
- j1939sr.c
Using j*smthng* for j1939-related tools is not very good for 2 reasons:
1. j prefix is not very informative;
2. jcat name is used by journal cat tool from popular sleuthkit toolkit;
2`. jacd sounds very similar to jackd.
2``. Possible future name conflicts for new tools.
Thus I renamed j* to j1939\1 to deal with this issue.
Signed-off-by: Alexander GQ Gerasiov <gq@cs.msu.su>
> Rename j* to j1939\1

- cangen.c
I had an idea to try and reproduce a problem I have with some bursty traffic and RX overrun erors. The bursty traffic is trying to mimic bursts of messages that might happen on CANOpen when multiple nodes sends their PDO messages as a reponse to a SYNC message.
Does this make sense to include in the cangen tool? If so here is a pull request.
Specify -c 100 to have 100 packets sent in a burst before gap.
To have a burst of 100 message with a gap of 200 milliseconds between each burst specify: -g 200 -c 100.
> cangen.c: added -c option for bursty output.

- cansniffer.c
Rework of cansniffer to support EFF CAN frames with 29 bit CAN identifiers.
The patch set addresses issue https://github.com/linux-can/can-utils/issues/181
> 29bit cansniffer

- Android.mk
Android now uses clang with Werror by default which prevents from
building.
Removing Werror for the current warnings.
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>
> Android.mk: fix Android 10 build

- can-j1939-kickstart.md
Incorrect value of the second databyte '23'
> can-j1939-kickstart.md: fix example in documentation

- j1939acd.c
- j1939cat.c
- j1939spy.c
- libj1939.c
- testj1939.c
Fix clang warnings in recently added j1939 files.
See Garys fixes here:
https://github.com/linux-can/can-utils/commit/43610bd6217cd8b38455ea9af6783fc04547929f
and here:
https://github.com/linux-can/can-utils/commit/46895a41c5241971f48bf936056de597d8190e29
> J1939 clang fixes

- j1939acd.c
Use include constant instead of hardcoded constant
> Changed hardcoded hex number 0x0fed8 to j1939.h constant "J1939_PGN_ADDRESS_COMMANDED"

- j1939acd.c
Reported-by: josemic <josemic@users.noreply.github.com>
> j1939acd: replace 0x0fed8 by constant J1939_PGN_ADDRESS_COMMANDED

- canfdtest.c
This avoids having the padding in the struct can_fame contain bogus
values, which are interpreted by "candump -x" as CAN-FD BRS and ESI
values.
> canfdtest: can_echo_gen(): initialize tx_frames with zero

- testj1939.c
without this patch we will always print "0008" on each line
> testj1939: print proper offset in the data damp

- canfdtest.c
This patch fixes the issue reported in:
https://github.com/linux-can/can-utils/commit/d7f28a0ffe36f73fe08729202f9c49ca5cac1dd4
https://github.com/linux-can/can-utils/issues/236
Reported-by: https://github.com/ronitnvidia
Fixes: d7f28a0ffe36 ("canfdtest: can_echo_dut(): check received frame for consistency")
> canfdtest: fix frame consistency check

- canfdtest.c
> canfdtest: bail out if trying to use non-existing CAN interface

- j1939cat.c
bzero is removed in POSIX 2008. malloc/bzero can also be replaced with
calloc.
> j1939cat: remove bzero

- bcmserver.c
- canlogserver.c
- isotpserver.c
usleep is removed in POSIX 2008.
> convert usleep to nanosleep

- asc2log.c
- cangw.c
- j1939acd.c
- testj1939.c
The former throws a pedantic warning.
> change {} to {0}

- Makefile
This patch fixes the indention, which was broken while renaming the j1939
tools.
Fixes: 8106214b5503 ("Rename j* to j1939\1")
> Makefile: fix indention

- .gitignore
- Android.mk
- CMakeLists.txt
- GNUmakefile.am
- Makefile
- README.md
- cansequence.c
The PTX flavour canutils have a useful utility for generating a sequence of CAN frames with an incrementing payload and checking such a sequence for missed and reordered frames.
Recently, it has helped finding a regression in the kernel pfifo_fast qdisc, which led to reordered frames.
To bring the utility to a greater audience, import the current state, including its history, into the linux-can set of utilities.
The supersedes @a3f's pull request https://github.com/linux-can/can-utils/pull/196.
> can-utils: import PTX cansequence utility

- log2asc.c
Fixes: 61dbb56ef694 ("log2asc: support DLC values in Classic CAN RTR frames")
> log2asc: fix spelling

- Android.mk
Otherwise throwing the following error:
build/make/core/base_rules.mk:325: error: external/can-utils:
MODULE.TARGET.EXECUTABLES.cansequence already defined by
external/can-utils.
Fixes: a726c2a ("Merge branch 'cansequence' of
github.com:marckleinebudde/can-utils into master")
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>
> Android.mk: remove duplicated cansequence definition

- cansequence.c
This patch fixes the following warning:
```
cansequence.c:232:3: warning: expression result unused [-Wunused-value]
(unsigned char)frame.data[0]++;
^              ~~~~~~~~~~~~~~~
```
> cansequence: do_send(): remove unneeded cast

- canlogserver.c
There is a small typo in canlogserver.c.
Should read `caught` rather than `cought`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, cought -> caught

- candump.c
Using epoll_wait() instead of select() gives higher performance for listening on multiple interfaces. Additionally, the read order has a higher chance to resemble the true temporal order. select() gives implicit priority to the lower index socket.
> candump: epoll_wait() instead of select() runs faster and better keeps packet order

- cangen.c
Use this for stress testing, when sending with two CAN controllers on the same CAN bus to avoid broken CAN frames due sending the same CAN-id.
> cangen: add possibility to generate random ID odd/even

- can-calc-bit-timing.c
This comment would have saved me a lot of time, when I was trying to figure out why the generated BRP in the table was twice of what it should be according to the datasheet.
I'm using a device with a 8 MHz crystal, thus the version of this tool that gets installed in Ubuntu 20.04 does not have the following commit: https://github.com/linux-can/can-utils/commit/3fc6c05ce244929b645ffd89d4e33a3511f6880d, which made it pretty confusing.
> Clarify that the mcp251x uses half of the external OSC clock as the base clock

- candump.c
Hello everyone, 
This may sound silly, but I just spend two hours debugging why this `-T` option won't terminate the process after specified timeout. Later I figured out it only terminates if nothing was received. A small change, but probably it saves some time to someone else.
> Update description for candump

- asc2log.c
This commit fixes this sort of lines
(1614188635.1000000) can1 4A8##28001E9A318ACC0 R
to become this
(1614188636.000000) can1 4A8##28001E9A318ACC0 R
Canplayer was barfing about the incorrect lines.
> asc2log: Correct usec overflow handling

- candump.c
-EINTR is not an error, just restart the syscall.
Fixes: 639498bc801a ("candump: use epoll_wait() instead of select()")
Link: https://github.com/linux-can/can-utils/issues/296
Reported-by: Joakim Zhang <qiangqing.zhang@nxp.com>
> candump: fix epoll_wait() returning -1, errno == -EINTR

- can-calc-bit-timing.c
This request adds can-calc-bittiming support for
* STM32 bxCAN
* C_CAN
* MCAN >=v3.1
> [v2] more chips bittiming

- canbusload.c
- canframelen.c
- canframelen.h
This MR adds (limited) CANFD support to the canbusload program.
1. set the socket in CANFD mode to receive all (up to 64) databytes
2. count the databits for BRS frames against the data bittiming
> [V2] canbusload with FD support

- mcp251xfd/mcp251xfd-main.c
Needed for the basename() function under musl.
> mcp251xfd: add missing libgen.h header

- CMakeLists.txt
This fixes compilation on musl libc.
Link: https://github.com/linux-can/can-utils/pull/326
Reported-by: Rosen Penev <rosenp@gmail.com>
> CMakeLists: unconditionally define _GNU_SOURCE

- libj1939.h
- testj1939.c
Reverted commit and added define to get the same types on all
platforms.
Fixes: eb9cfac9543b ("use PRIx64")
> testj1939: fix 64-bit types for some platforms

- libj1939.h
Fixes: e370ad5256f4 ("testj1939: fix 64-bit types for some platforms")
> libj1939.h: fix typo

- cangw.c
- cansniffer.c
- include/linux/can/isotp.h
- isotpdump.c
- isotpperf.c
- isotprecv.c
- isotpsend.c
- isotpserver.c
- isotpsniffer.c
- isotptun.c
- update isotp.h include file
- update maximum PDU (buffer) size to 64kByte buffer
- support setting of N_As (frame_txtime) to zero
> isotp: support Linux 5.18 features

- .github/workflows/codeql-analysis.yml
- asc2log.c
- lib.c
```
mkdir build && cd build
CC=clang cmake -DCMAKE_C_FLAGS="-fsanitize=address,undefined" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined" .. && cmake --build .
```
```
$echo "(0.0) can1 ffffffff#00000000" | ./log2long 
can-utils/lib.c:187:23: runtime error: left shift of 15 by 28 places cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /can-utils/lib.c:187:23 in 
(0.0)  can1  3FFFFFFF   [4]  remote request
```
cast to unsigned value
`cf->can_id |= ((canid_t)tmp << (7-i)*4);`
```
mkdir build && cd build
CC=clang cmake -DCMAKE_C_FLAGS="-fsanitize=address,undefined" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined" .. && cmake --build .
```
```
$echo "echo "0.0000 0  Rx   d 8 8D 00 10 01 00 82 01 00 …
```
> Fixed some undefined behavior and added CodeQL workflow

- lib.c
adding cast preventing int/unsigned comparison (-Wsign-compare warning in lib.c)
If "-Wsign-compare" warnings break the Android build because of Werror there, maybe Wsign-compare should be added to the CFLAGS in the default build to be aware of sign-compare issues. Should I add this flag? 
can-calc-bit-timing.c and mcp251xfd-dump.c also produce sign-compare warnings in my local build.
>  fix for issue #369

- Android.mk
- CMakeLists.txt
Fixes: 9c38c16437e9 ("can-calc-bit-timing: move into subdir")
Reported-by: Tompee Balauag <tompee26@gmail.com>
Link: https://github.com/linux-can/can-utils/issues/373
> Android.mk: fix compilation of can-calc-bit-timing

- lib.c
When multiple error flags are set, snprintf_error_data created a comma
seperated textual presentation of it. Commit ef853f555379 ("added return value
check of snprintf to prevent possible buffer overflows detected by CodeQL")
removed the increment of count, so the delimiter is no longer added. Fix this
by incrementing count again.
Fixes: ef853f555379 ("added return value check of snprintf to prevent possible buffer overflows detected by CodeQL")
Signed-off-by: Jeroen Hofstee <jhofstee@victronenergy.com>
> lib: fix seperator in snprintf_error_data

- candump.c
Reported-by: https://github.com/HBLocker
Link: https://github.com/linux-can/can-utils/issues/379
> candump: main(): fix scope of fname

- cangen.c
This reverts commit 1f96d674c0cb7b60ee315981f12a7feb94829697.
Link: https://github.com/linux-can/can-utils/pull/396
Link: https://github.com/linux-can/can-utils/commit/1f96d674c0cb7b60ee315981f12a7feb94829697#commitcomment-97455025
> Revert "cangen: use if_nametoindex() to avoid overflows"

- cangen.c
Fixes: f55ea38d146a ("cangen: add option for absolute timeouts")
Fixes: c6f2cf7c2f27 ("cangen: add support for SO_TXTIME")
> cangen: print_usage(): add missing newlines

- Android.mk
> [fix] Adding lib.c to rule of slcanpty build for AOSP / AAOS

- cangen.c
| cangen.c: In function ‘parse_dataoptarg’:
| cangen.c:422:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
|   for (int i = 0; i < CANFD_MAX_DLEN && i < arglen / 2; i++) {
|   ^
| cangen.c:422:2: note: use option -std=c99 or -std=gnu99 to compile your code
| cangen.c: In function ‘main’:
| cangen.c:796:4: error: ‘for’ loop initial declarations are only allowed in C99 mode
|     for (int i = 0; i < frame.len; i++) {
|     ^
Reported-by: https://github.com/yannS2016
Link: https://github.com/linux-can/can-utils/issues/428
Fixes: e409aa4c8c31 ("cangen: new generation mode - partially randomized payload (-D)")
> cangen: main(): avoid loop initial declaration

- CMakeLists.txt
- GNUmakefile.am
- Makefile
- check_cc.sh
- configure.ac
- fork_test.c
Systems that lack a MMU cannot use fork() to create the child process. First we detect if the toolchain has the fork() symbol and if it does not, we just always use vfork().
> Add support for Linux/no-mmu with vfork

- canbusload.c
When canbusload is executed without bit rate, it exits with an exit code of 1 and prints help, but without explaining why.  Users cannot know what was wrong.  When other errors occur, though, canbusload prints an error message along with the help.
Print an error message when bit rate is not given or "@" is not found.
> canbusload: Enhance error message for missing bitrate

- candump.c
By using C99 initializers for struct sockaddr_can addr the not assigned members are automatically set to 0x0, resulting in not passing uninitialized memory to the bind() syscall.
> candump: main(): use C99 initializers for struct sockaddr_can addr

- .clang-format
- canplayer.c
Hi,
I use the `canplayer` daily, and as a result, there are some features I'd like to implement(flag to start candump at desired timestamp; show progress in command-line). I'm currently adding these features to the `canplayer`. However, while working with the codebase, I noticed areas where the code structure and formatting could benefit from enhancements for improved readability and maintainability. In this pull request, I've introduced some formatting changes and added a `.clang-format` file, which I've applied to `canplayer.c`.
My primary goal is to contribute positively and uplift the code quality. In an upcoming pull request, I plan to remove the `goto` statements and further refactor the code. I believe that with additional adjustments, we can further refine the codebase, and I'm …
> Format code of canplayer

- cansequence.c
It's not implemented and no other of the can-utils support it, so remove it.
> cansequence: remove --version option from help test

- cansequence.c
It is not implemented and not supported by any of the can-utils, so remove it.
> cansequence: remove --version option from help text

- cansequence.c
Streamline error messages for failing syscalls.
> cansequence: error messages

- calc-bit-timing/can-calc-bit-timing.c
In 913311fc15a2 ("can-calc-bit-timing: add support to decode user supplied bit timing parameters") support to decide user supplied bit timing parameters was added. However, it was forgotten to add --tq to the help text.
Add help text for the --tq paramter.
Reported-by: https://github.com/EnricoMontecaggi
Closes: https://github.com/linux-can/can-utils/issues/459
Fixes: 913311fc15a2 ("can-calc-bit-timing: add support to decode user supplied bit timing parameters")
> can-calc-bit-timing: print_usage(): add --tq parameter to help text

- canbusload.c
We don't need to block any signals, so a select() is sufficient. This also fixes the problem that sigmask is uninitialized and may block the sig ARLM, which make canbusload hang until a CAN frame is recieved.
Closes: https://github.com/linux-can/can-utils/issues/465
> canbusload: main(): switch from pselect() to select() to avoid blocking sig ARLM

- cansequence.c
In the CAN universe, most data is displayed in hex. Change the verbose output to hex, to ease debugging.
> cansequence: print counter received data as hex

- asc2log.c
- candump.c
- canlogserver.c
- canplayer.c
- isotpdump.c
- isotpperf.c
- isotpsniffer.c
- j1939cat.c
- j1939spy.c
- log2asc.c
- slcanpty.c
Using C99 `unsigned long long` to format `struct timeval`'s `tv_sec` and `tv_usec`, fix incorrect print under some 32bit platform which using time64.
To fix issue #469. It may looks ugly, but straightforward.
> timestamp formatting: always use 64-bit for timesstamp formatting.

- calc-bit-timing/can-calc-bit-timing.c
Add timing parameters for CAN-FD controller found on Rockchip SoCs.
> can-calc-bit-timing: add rockchip_canfd

- cansequence.c
Fixes: 642190647e8e ("cansequence: add option to ignore classical CAN frames")
> cansequence: add missing "--strict" to long_options

- canfdtest.c
Also use `can0` as default interface.
> canfdtest: fix filter for extended frames and some cleanups

- canfdtest.c
Use the correct flag MSG_CONFIRM to detect frames generated on this socket.
Fixes: c35ed80b3d25 ("canfdtest: use struct msghdr::msg_flags to detect own frames")
> canfdtest: fix detection of own frames

- isobusfs/isobusfs_cmn_dh.c
- isobusfs/isobusfs_srv_cm.c
Fixes musl build for ARMv7:
When attempting to build as follows:
```shell
DIR_ARTIFACTS=/tmp/artifacts/armv7l
ARCH_BUILD=$(gcc -dumpmachine) # x86_64-linux-gnu
ARCH_HOST=armv7l-linux-musleabihf
make distclean
./autogen.sh
./configure --build $ARCH_BUILD --host $ARCH_HOST LDFLAGS="-static"
make
```
the struct `timespec` can not be resolved. The includes fix this.
See also 0e0a033993a4858a289a6663a43bf2e09704a2b1
> Fix musl armv7 build: Include time.h in isobusfs_{cmn_dh,srv_cm}

- mcp251xfd/mcp251xfd-regmap.c
Fix the following compiler warning:
```
mcp251xfd/mcp251xfd-regmap.c:38:4: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
fscanf(reg_file, "%*[^\n]\n");
^~~~~~ ~~~~~~~~~~~~~~~~~~~~~
```
Reported-by: https://github.com/Chaitanya84
Link: https://github.com/linux-can/can-utils/pull/506
> mcp251xfd-regmap: fix compiler warning

- isobusfs/isobusfs_srv_fa.c
Fix following clang warnings:
```
CC       isobusfs/isobusfs_srv_fa.o
isobusfs/isobusfs_srv_fa.c:387:6: warning: variable 'handle' is used
uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
if (ret < 0) {
^~~~~~~
isobusfs/isobusfs_srv_fa.c:411:15: note: uninitialized use occurs here
res.handle = handle;
^~~~~~
isobusfs/isobusfs_srv_fa.c:387:2: note: remove the 'if' if its condition is
always false
if (ret < 0) {
^~~~~~~~~~~~~~
isobusfs/isobusfs_srv_fa.c:368:6: warning: variable 'handle' is used
uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
if (name_len > ISOBUSFS_MAX_PATH_NAME_LENGTH) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
isobusfs/isobusfs_srv_fa.c:411:15: note: uninitialized use occurs here
res.handle = handle;
^~~~~~ …
```
> isobusfs: fix clang warnings

- calc-bit-timing/can-calc-bit-timing.c
Link: https://github.com/linux-can/can-utils/issues/518
Reported-by: https://github.com/EnricoMontecaggi
Fixes: f4a9e5b57def ("can-calc-bit-timing.c: Reformat help/usage output to be compatible with help2man.")
> can-calc-bit-timing: in case of invalid option exit with error

- isobusfs/isobusfs_cli.c
- isobusfs/isobusfs_srv.c
- isobusfs/isobusfs_srv_cm.c
This pull request should address following issues:
https://github.com/linux-can/can-utils/issues/529
and one detected by introducing errors on the CAN bus
https://github.com/linux-can/can-utils/issues/443
> Isobusfs fixes

- CMakeLists.txt
- cmake/make_uninstall.cmake
Improve indentation according to the .editorconfig style.
Write commands in lowercase letters.
Break long lines.
Remove double keywords (PRIVATE).
> CMake: resolve linting issues

- bcmserver.c
closes: https://github.com/linux-can/can-utils/issues/516
>  bcmserver: use pragma to silence gnu-variable-sized-type-not-at-end warning

- isobusfs/isobusfs_cmn.c
Modify the isobusfs_log function in isobusfs_cmn.c to explicitly limit the lengths of the time_buffer, level_str, and log_entry strings in the snprintf format string to 40, 10, and 150 characters respectively. This change acknowledges that truncation may still occur, but it is now explicit and controlled.
This change silences the following warning:
```
cmake -DCMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=gcc -B build
cmake --build build
/home/isobusfs/isobusfs_cmn.c: In function 'isobusfs_log': /home/isobusfs/isobusfs_cmn.c:104:30: warning: '%s' directive output may be truncated writing up to 191 bytes into a region of size between 182 and 245 [-Wformat-truncation=]
104 |                  "[%s] [%s]: %s", time_buffer, level_str, log_entry);
|                              ^~ …
```
> isobusfs: address snprintf truncation warning with explicit limits

- CMakeLists.txt
- include/linux/kernel.h
- isobusfs/isobusfs_cli.c
- isobusfs/isobusfs_cli.h
- isobusfs/isobusfs_cmn.c
- isobusfs/isobusfs_cmn.h
- isobusfs/isobusfs_srv.c
- isobusfs/isobusfs_srv.h
- isobusfs/isobusfs_srv_cm.c
- j1939_timedate/j1939_timedate_cli.c
- j1939_timedate/j1939_timedate_cmn.h
- j1939_timedate/j1939_timedate_srv.c
- j1939cat.c
- libj1939.c
- libj1939.h
Add support for J1939 TimeDate protocol. It allow  to read Time and Date on the remote system over J1939 protocol.
By the way, i moved some of ISOBUS FS code, to be able to reuse this code in the TimeDate application.
Since i'm not good at making proper Build configs i modified only GNUmakefile.am file. It would be good if some one
can help to update other make files. Or even drop some of them?
> Add support for the J1939 TimeDate services

- asc2log.c
the get_date function misses a case when the date line having AM in timestamp. This PR fixes that problem by finding ` am ` in the date string.
> asc2log::get_date check for AM in en_US time format

- j1939acd.c
- j1939sr.c
* j1939acd: remove legacy '-p' option (prefix to use when logging)
- remove legacy '-p' option (prefix to use when logging), fixes uclibc
compile
Fixes:
j1939acd.c: In function 'main':
j1939acd.c:489:38: error: passing argument 1 of 'asprintf' from incompatible pointer type [-Wincompatible-pointer-types]
489 |                         if (asprintf(&program_invocation_name, "%s.%s",
|                                      ^~~~~~~~~~~~~~~~~~~~~~~~
|                                      |
|                                      const char **
* j1939sr: remove legacy program_invocation_name/program_invocation_short_name code
> j1939acd: remove legacy '-p' option (prefix to use when logging)

- README.md
The can.txt is obsolete, move to rendered html instead.
> README: update link to kernel documentation

- .github/workflows/codeql-analysis.yml
v1 is deprecated. Thus, use the latest version v3 instead.
> CI: fix codeql-analysis

- libj1939.h
Fixes
git/isobusfs/../libj1939.h:33:18: error: field has incomplete type 'struct timespec'
33 |         struct timespec next_send_time;
|                         ^
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> Include time.h for timespec struct definition

- isobusfs/isobusfs_cli_int.c
- isobusfs/isobusfs_cli_selftests.c
- isobusfs/isobusfs_cmn.c
- isobusfs/isobusfs_cmn_dh.c
- isobusfs/isobusfs_srv.c
- isobusfs/isobusfs_srv_dh.c
- isobusfs/isobusfs_srv_fa.c
Typos were found with codespell.
> isobusfs: fix typos

- .github/workflows/compile.yml
- CMakeLists.txt
- Makefile
- j1939_vehicle_position/j1939_vehicle_position_cmn.h
- j1939_vehicle_position/j1939_vehicle_position_srv.c
- libj1939.c
- libj1939.h
This patch set provide support for the GPSD to J1939 service. I managed to make CmakeList work so far, but i still need help to make Makefile work properly too. How to manage properly gpsd dependecy, currenty i do not know.
> J1939 vehicle position

- .github/workflows/compile.yml
Fixes: 130e0dced288 ("github-actions: compile with gcc and clang using Makefile")
> github-actions: fix used compiler

- README.md
This PR modifies the README.md to:
- Document the existence of `canerrsim` CAN error simulation tool
- Add hyperlink to existing J1939 kernel module Debian installation document
> README.md : mention new canerrsim tool and add a link to existing J1939 kernel module installation document

- slcand.c
On some systems `SIOCGIFNAME` may fail with `ENOTTY`, but the actual
`slcanX` interface gets properly configured. Instead of crashing hard
on such case, let's gracefuly degrade and just not display the
interface name.
This is the issue I mentioned in https://github.com/linux-can/can-utils/pull/118
> Don't fail when it wasn't possible to fetch the interface name.

- calc-bit-timing/can-calc-bit-timing.c
There are real world use cases for CAN-FD data bitrates below 1 MBit/s. Add some to the `common_data_bitrates` array.
Link: https://lore.kernel.org/79BCE02A-D4EC-4362-B0D3-3FE76FB17B78@vpprocess.com
> can-calc-bit-timing: common_data_bitrates: add some slower bitrates

- CMakeLists.txt
- README.md
Currently the CMake build is either all or nothing. You have explicit control over which targets are built using `cmake --build --target <xyz>`, but this doesn't apply to install step.
Running `cmake --install` will currently always install all available targets.
This PR adds the same groups that are present in the README to the CMake build, allowing you to control them individually. By default everything is turned on, which means there should be no differences compared to before.
> Allow more fine-grained control over CMake targets
