linux-can/can-utils

lib.c
lib.h

pointer to const in lib

---

canfdtest.c

This patch fixes this bug
https://github.com/linux-can/can-utils/issues/13
Modified the existing millisleep function to use clock_nanosleep with
MONOTONIC clock and relative timeout.
Signed-off-by: Ramesh Shanmugasundaram <ramesh.shanmugasundaram@bp.renesas.com>

canfdtest: remove usage of gettimeofday

---

lib.c

Used same macro instead of array

Another macro usage

---

cansniffer.c
jacd.c
jsr.c
slcan_attach.c
slcand.c

Add missing return value checks

---

jcat.c

it was if(offset != NULL), so it should be if(offset)

jcat: inverse if logic

---

isotpdump.c

Adds the option -u to isotpdump which will print the UDS message type as well as the service name or response code.

Add uds output functionality

---

can-calc-bit-timing.c
canfdtest.c
jcat.c
slcand.c
slcanpty.c

This way all licenses in the project will be homogenised.
See the initial discussion in #143.
Acked-by: Marc Kleine-Budde <mkl@pengutronix.de>
Acked-by: Oliver Hartkopp <socketcan@hartkopp.net>
Acked-by: Sven Schmitt <sven.schmitt@gmx.net>
Acked-by: Oleksij Rempel <ore@pengutronix.de>
Acked-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Acked-by: Brennan Ashton <bashton@brennanashton.com>
Acked-By: IOhannes m zmölnig <zmoelnig@iem.at>
Acked-by: Frank Theile <ftheile@grundfos.com>
Acked-by: Wolfgang Grandegger <wg@grandegger.com>
Acked-by: Jeremiah Mahler <jmmahler@gmail.com>
Acked-by: Jonathan Challinger <mr.challinger@gmail.com>
Acked-by: Cheng-Lung Lee <chenglung@gmail.com>
Acked-by: Ramesh Shanmugasundaram <rashanmu@gmail.com>
Acked-by: Mans Rullgard <mans@mansr.com>
Acked-by: …

Relicense GPL-2.0-or-later files to GPL-2.0-only

---

README.md

Fix socketcand URL and add cannelloni.

README: update the list of CAN over IP tools

---

LICENSES/BSD-3-Clause
LICENSES/GPL-2.0-only.txt
LICENSES/Linux-syscall-note.txt
libj1939.h

This patch series fixes some of the issues mentioned by the REUSE utility

Reuse fixes

---

include/linux/can.h
include/linux/can/bcm.h
include/linux/can/error.h
include/linux/can/gw.h
include/linux/can/j1939.h
include/linux/can/netlink.h
include/linux/can/raw.h
include/linux/can/vxcan.h

include: import header files from kernel v5.4-rc7

---

candump.c

The tool 'candump' is used to dump CAN traffic to stdout or logfile.
In early days where the in-kernel CAN gateway (can-gw) with the cangw tool was
not yet implemented the bridging functionality allowed to send received (and
filtered) CAN frames to another outgoing CAN interface.
As we now have can-gw and sending CAN frames from a 'reading tool' seems wrong
especially from the Unix philosophy "Write programs that do one thing and do
it well." this patch removes the obsolete functionality from candump.

candump: remove bridging functionality

---

canbusload.c
candump.c
cangw.c
canlogserver.c
canplayer.c
cansend.c
cansniffer.c
include/linux/netlink.h
isotpperf.c
lib.c
log2asc.c

See below my patches to fix the warnings. Let me know your thoughts.

Fix warnings

---

j1939acd.c

Fix bug:
https://github.com/linux-can/can-utils/issues/206

J1939acd verbose

---

j1939acd.c

Picking up @josemic work https://github.com/linux-can/can-utils/pull/222

j1939acd help text improvements

---

j1939cat.c

Allow to use j1939cat to send and receive broadcast (TP.BAM) messages.

j1939cat: add broadcast support

---

.travis.yml

travis: fix indention

---

asc2log.c
bcmserver.c
isotpperf.c
isotpserver.c

It makes more sense to return before hitting else.

custom if statement reordering

---

.travis.yml

Fixes: b7ba7f32fc8e ("added script to run on power")

travis: fix env for ppc64le

---

j1939cat.c

add missing time.h include

---

canplayer.c

Wait for ENTER key to process next CAN frame from the log file.
As the new line is printed each time this approach doesn't win a
design price. But this feature is very uncommon and setting the
terminal into some raw mode to get the raw keyboard hits would
introduce a big code overhead to handle e.g. CTRL-C signals which
is a vital functionality for canplayer.
Link: https://github.com/linux-can/can-utils/issues/280
Suggested-by: https://github.com/nico0481

canplayer: add interactive single-step frame processing mode

---

testj1939.c

This is the proper specifier for uint64_t.

use PRIx64

---

isotpsend.c

To generate high load PDU traffic for kernel testing.

isotpsend: add new options to generate PDU traffic load

---

candump.c

Link: https://github.com/linux-can/can-utils/pull/345
Suggested-by: https://github.com/xR3b0rn

candump: add option to define individual filename for logfile

---

canfdtest.c

Add the '-d' command line option that allows to transmit CAN FD frames instead of CAN 2.0 frames. The frames content is the same.
This allows to stress test the flexible data rate part of a CAN FD network.
These changes have been tested on Ubuntu 20.04 and Ubuntu 22.04 using a `vcan` interface and Wireshark. The CAN FD frames generation has also been checked on a custom board with a hardware CAN analyzer.

canfdtest: Add CAN FD support

---

canfdtest.c

Added the '-b' command line option, to be used in conjunction with the '-d' option that enables CAN FD, to set the BRS bit in a CAN FD frame.
When enabled, the data part of the CAN FD frame is transmitted at a higher speed.
All remaining parts of the CAN FD frame use the classic CAN speed.

canfdtest: Add CAN FD Bit Rate Switch support

---

canfdtest.c

Added the '-s' command line option to set the frame payload length in bytes.

canfdtest: Add message length support

---

canfdtest.c

Added the '-e' command line option to enable 29-bit CAN ID.

canfdtest: Add extended frame format support

---

cangen.c

Various `cangen` cleanup, preparation to add more features.

cangen cleanups

---

slcan_attach.c
slcand.c

SLCAN - Increase BTR char limit to 8 for 32bit BTR

---

README.md
canlogserver.c

Update the description of canlogserver in README.md and help message.
This closes #421.

canlogserver: Update the description

---

cansequence.c

- add C99 initializers to clear memory
- add support for "any" interface

cansequence improvements

---

candump.c
canfdtest.c
cangen.c
cansend.c

Convert some tools towards kernel coding style.

Codingstyle

---

lib.c

This fixes a compile error and a warning on Android 13 in a termux environment.

Fix compilation on Android

---

.gitignore
CMakeLists.txt
GNUmakefile.am
Makefile

Closes: https://github.com/linux-can/can-utils/issues/497

isobus: clean up build system integration, fix cmake

---

testj1939.c

Modify the verbose information for setting the promiscuous mode option;

testj1939: correct verbose information

---

.editorconfig

Handles source and CMake files.

Add configuration file for EditorConfig

---

isobusfs/isobusfs_cmn.c
j1939spy.c

Fix 2 compiler errors that were found while working on the new CI integration.

Fix compiler errors

---

isotpdump.c

add option '-b' to capture functional broadcast data eg: `-b 98DAFFF1` or `-b 18DAFFF1`
there are 3 can_id used during FOTA by UDS over J1939: 
`18DATTSS`, `18DASSTT` and `18DBFFSS` (or `18DB33SS`, functional addressing)
value `TT` is the target address and `SS` is the source address for J1939 can_id. 
add this option to capture all these traffic

isotpdump: option to capture functional addressing traffic

---

canplayer.c

Depends on the nanosecond patch

Fix possible sscanf buffer overflow
